### ISSUE TITLE
doc example doesn't work

### ISSUE THREAD

**Issue by tisdall** [Pylons/colander#231]
Trying out [an example in the docs](http://docs.pylonsproject.org/projects/colander/en/latest/basics.html?highlight=schema_type#subclassing-schemanode) I get the following:

```
>>> ranged_int = colander.SchemaNode(
...     schema_type=colander.Int,
...     validator=colander.Range(0, 10),
...     default=10,
...     title='Ranged Int'
...     )
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/colander/__init__.py", line 1817, in __init__
    self.typ = self.schema_type()
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/colander/__init__.py", line 1833, in schema_type
    'Schema node construction without a typ argument or '
NotImplementedError: Schema node construction without a typ argument or a schema_type() callable present on the node class 
```

related to #229

**Comment by mmerickel** [comment]
The doc example is fixed. Sorry but I don't want to add doctests, they're not a pattern I'm comfortable with especially if they don't work with the existing `code-block` directive.
