### ISSUE TITLE
ImportError: cannot import name 'Utc'

### ISSUE THREAD

**Issue by jomasti** [Pylons/colander#294]
Hi, when pulling down Colander and importing it, I get `ImportError: cannot import name 'Utc'`. Presumably, it's because of a new release of iso8601 (0.1.12, 5 hours ago) and the lack of version pinning for it. It includes [this commit](https://bitbucket.org/micktwomey/pyiso8601/commits/a1f771bc36754edb2fd649ab2fbe6b788b6c6149) that removes that class for Python versions ≥ 3.2.

For completeness:

Python version: 3.4
Colander version: 1.3.1
Stack trace:
```
Traceback (most recent call last):
  File "/home/josh/project/env/lib/python3.4/site-packages/_pytest/config.py", line 325, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/home/josh/project/backend/tests')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/josh/project/env/lib/python3.4/site-packages/_pytest/config.py", line 356, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/home/josh/project/backend/tests/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/josh/project/env/lib/python3.4/site-packages/_pytest/config.py", line 362, in _importconftest
    mod = conftestpath.pyimport()
  File "/home/josh/project/env/lib/python3.4/site-packages/py/_path/local.py", line 662, in pyimport
    __import__(modname)
  File "/home/josh/project/env/lib/python3.4/site-packages/_pytest/assertion/rewrite.py", line 216, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/home/josh/project/backend/tests/conftest.py", line 12, in <module>
    from josh/project.models import (
  File "/home/josh/project/backend/josh/project/__init__.py", line 17, in <module>
    from josh/project.api.auth.single_sign_on import SSOAuthenticationPolicy
  File "/home/josh/project/backend/josh/project/api/__init__.py", line 2, in <module>
    import colander
  File "/home/josh/project/env/lib/python3.4/site-packages/colander/__init__.py", line 21, in <module>
    from . import iso8601
  File "/home/josh/project/env/lib/python3.4/site-packages/colander/iso8601.py", line 3, in <module>
    from iso8601.iso8601 import (parse_date, ParseError, Utc, FixedOffset, UTC, ZERO, ISO8601_REGEX)
ImportError: cannot import name 'Utc'
ERROR: could not load /home/josh/project/backend/tests/conftest.py
```

**Comment by ho1ger** [comment]
Can confirm this problem for colander 1.3.3 and  iso8601 > 0.1.12

**Comment by akalex** [comment]
Any updates on this issue?

**Comment by akalex** [comment]
It seems issue not with Colander but with iso8601. It was updated recently. Works fine for colander 1.3.3 and iso8601 0.1.11

**Comment by ztane** [comment]
There was some fsckup with the code there; python 2 branch defines Utc; then UTC = Utc(); Python 3 doesn't.

**Comment by tseaver** [comment]
Hmm, we don't actually *use* `Utc`, `ZERO`, or `FixedOffset`:  why are we attempting to re-export them?

**Comment by tseaver** [comment]
In fact, `deform` no longer tries to import `colander.iso8601`:  I'm beginning to believe we should just delete the module altogether.
